language: node_js
node_js:
- node
cache: npm
script: npm run deploy
after_script: npm run alias
env:
  global:
  - secure: CfIW+7doMSR4Wsh2OILct80sEbADHVH0pTEYtaXJ568dLHow5r0cX2hEb7ZHa4lIuzd512UboPI9hsejH/pCJmJ8CaoI8JSQA1B3ZTVWWPWvTATjD92Cb5e1wGoGr9Hk2b5KMuHWXGPOKiAiZtxeE1Dy8LmZ4MFjTvnTsj18KPRApPd+oc36EcuAWJBM3/vtw/1sF86RtkyJADx3cOHwhHS4jWfZKrnQ+RVcS31WCOgQUhWPxX1CIbMtj7/IiXxgzqbSCyvGGXzwQlnpOPJOiUNum+S+n4pMV7HyqdlSqHAg97ZyYb7YjFyImDpZS5wChNdYSArqC51IgoLkLx5juiLLPAW+0elQ7YSyVUloybArDvE3VvNRFGzZQJodjhcR2N6jFWmxyVj5UaG80PEF9xYj4owoGwWy6r0Lbcvq43t/B+0kiEO2D7I1P0LYmATrHUsr0c8275aWlIxuyxY1NVwxnmgd1qkf6QBQ0opTSA587+8m9LzIjo5z8nNKFqncXN40siW42emocTauw4fTCKVNpUxsPWg1zBDtkcNFhJKHz8SJ0p/hqGfN7wcUW0JEUmc1FhoQr8oC9aoHaEnRO0kiVebd1lmfTEYKC1seCFWLbF+RYQfmHrN9BOHSXoqN+d7si+Chtl75J/xvYvOEAX14EcFO7aKRrsnqYvtV0iY=
